DROP TABLE IF EXISTS students;

CREATE TABLE students (
    /* id INTEGER PRIMARY KEY AUTOINCREMENT,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    content TEXT NOT NULL,
    */
    student TEXT NOT NULL
    
);